/**
 * Emits Merkle fixtures for the program's Rust tests.
 *
 *   pnpm catalog:fixtures           regenerates data/test-fixtures.json
 *   pnpm catalog:fixtures --check   fails if it differs from the committed one
 *
 * This file is the whole point of testing the program in Rust (see the PG-06
 * ADR): the TypeScript catalog is the reference implementation, and the Rust
 * program must accept exactly the proofs it produces. If the two ever diverge
 * — pair ordering, leaf prefix, endianness — these fixtures stop verifying.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fromRepoRoot } from '@eternal-word/shared'
import {
  buildChapterRootsTree,
  buildChapterTrees,
  chapterRootProof,
  encodeChapterRootLeaf,
  encodeVerseLeaf,
  proofForAddress,
  toHex,
} from '../canonical-merkle.js'
import { listOmittedPositions, listRegistrableVerses, loadCanonicalBooks } from '../dataset.js'

const ARTIFACT_PATH = fromRepoRoot(import.meta.url, 'data/test-fixtures.json')

/** Chapters chosen to cover the shapes that break naive implementations. */
const SAMPLE: readonly (readonly [number, number, string])[] = [
  [1, 1, 'first chapter of the canon — leaf index 0'],
  [19, 119, 'largest chapter (176 verses), deepest per-chapter tree'],
  [66, 22, 'last chapter of the canon — last leaf index'],
  [17, 8, 'holds the longest verse (Esther 8:9)'],
  [31, 1, 'single-chapter book (Obadiah)'],
]

const books = loadCanonicalBooks()
const verses = listRegistrableVerses(books)
const chapters = buildChapterTrees(verses)
const commitment = buildChapterRootsTree(chapters)

/** Verses chosen for the shapes that matter to `register_verse`. */
const VERSES: readonly (readonly [number, number, number, string])[] = [
  [1, 1, 1, 'first verse of the canon'],
  [17, 8, 9, 'longest verse — the transaction budget worst case'],
  [19, 119, 176, 'last verse of the largest chapter, deepest proof'],
  [66, 22, 21, 'last verse of the canon'],
]

const artifact = {
  note: 'Generated by pnpm catalog:fixtures. Consumed by the Rust tests of the Anchor program.',
  rootsCommitment: toHex(commitment.root),
  leafEncoding: 'book:u8 | chapter:u16le | root:32',
  chapters: SAMPLE.map(([book, chapter, why]) => {
    const tree = chapters.find((c) => c.book === book && c.chapter === chapter)
    if (tree === undefined) throw new Error(`chapter not in the canon: ${book}:${chapter}`)
    return {
      why,
      book,
      chapter,
      root: toHex(tree.tree.root),
      leaf: toHex(encodeChapterRootLeaf(book, chapter, tree.tree.root)),
      proof: chapterRootProof(chapters, book, chapter).map(toHex),
    }
  }),
  verses: VERSES.map(([book, chapter, verse, why]) => {
    const tree = chapters.find((c) => c.book === book && c.chapter === chapter)
    if (tree === undefined) throw new Error(`chapter not in the canon: ${book}:${chapter}`)
    const found = tree.verses.find((candidate) => candidate.address.verse === verse)
    if (found === undefined) throw new Error(`verse not in the canon: ${book}:${chapter}:${verse}`)
    return {
      why,
      book,
      chapter,
      verse,
      text: found.text,
      textBytes: Buffer.byteLength(found.text, 'utf8'),
      leaf: toHex(encodeVerseLeaf(found.address, found.text)),
      chapterRoot: toHex(tree.tree.root),
      proof: proofForAddress(tree, found.address).map(toHex),
    }
  }),
  /** Positions the WEB leaves empty. They have no leaf, so no proof exists and
   * registration must be impossible — not special-cased, simply unprovable. */
  omitted: listOmittedPositions(books).map((address) => ({
    book: address.book,
    chapter: address.chapter,
    verse: address.verse,
  })),
}

const serialized = `${JSON.stringify(artifact, null, 2)}\n`

if (process.argv.includes('--check')) {
  if (readFileSync(ARTIFACT_PATH, 'utf8') !== serialized) {
    process.stderr.write(
      'Test fixtures are stale — the catalog changed but data/test-fixtures.json did not.\n' +
        'Run `pnpm catalog:fixtures` and review the diff.\n',
    )
    process.exit(1)
  }
  process.stdout.write(`fixtures reproducible — commitment ${artifact.rootsCommitment}\n`)
} else {
  writeFileSync(ARTIFACT_PATH, serialized)
  process.stdout.write(`wrote ${ARTIFACT_PATH}\n`)
}
